kind: BuildConfig
apiVersion: v1
metadata:
  name: ocp-tutorial-pipeline
  labels:
    app: ocp-tutorial
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  source:
    git:
      ref: master
      uri: "https://github.com/M7md3mmar/ocp-tutorial.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
      - name: SERVICE_URI
        value: http://ocp-tutorial:9080       
